[package]
name = "mistql"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
pest = "2.0"
pest_derive = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"